### ISSUE TITLE
Dataset Conversion dose not work

### ISSUE THREAD

**Issue by ttt-ishi03** [JonasKrug/Light-Skeleton-Detection#1]
I am unable to convert the dataset. It seems that either the download URL for the dataset is incorrect, or the dataset has been updated. 

Specifically, when I run "convert_training_data_and_clean_up.sh", the following error message is displayed:

```
Traceback (most recent call last):
  File "/home/[user_name]/Light-Skeleton-Detection/training/datasets/Apollo3D/apollo3D_to_LSD_labelstudio.py", line 288, in <module>
    main()
  File "/home/[user_name]/Light-Skeleton-Detection/training/datasets/Apollo3D/apollo3D_to_LSD_labelstudio.py", line 271, in main
    data = load_apollo_3d(apollo_annotation_file_train)
  File "/home/[user_name]/Light-Skeleton-Detection/training/datasets/Apollo3D/apollo3D_to_LSD_labelstudio.py", line 174, in load_apollo_3d
    return json.load(open(apollo_annotation_file))
FileNotFoundError: [Errno 2] No such file or directory: './train/annotations/apollo_keypoints_66_train.json'
```

The folder structure that can be downloaded with download_training_data.sh is currently (as of 2024/2/25) as follows:
```
train
├── camera
│   └── camera_intrinsic.txt
├── car_poses
│   ├── 171206_034625454_Camera_5.json
│   ├── 171206_034630104_Camera_5.json
│   ├── ( other json files )
---
└── ignore_mask
    ├── 171206_034625454_Camera_5.jpg
    ├── 171206_034630104_Camera_5.jpg
    ├── ( other jpg files )
---
```

**Comment by ttt-ishi03** [comment]
I overlooked a part in the README. This issue is incorrect.
